"""empty message

Revision ID: c327bba3ec85
Revises: 31f4c76aa529
Create Date: 2020-09-30 07:03:16.554663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c327bba3ec85'
down_revision = '31f4c76aa529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('citystate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'citystate', ['citystate_id'], ['id'])
    op.drop_constraint('citystate_venue_id_fkey', 'citystate', type_='foreignkey')
    op.drop_column('citystate', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citystate', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('citystate_venue_id_fkey', 'citystate', 'Venue', ['venue_id'], ['id'])
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'citystate_id')
    # ### end Alembic commands ###
