"""empty message

Revision ID: ee718e58c434
Revises: c327bba3ec85
Create Date: 2020-09-30 07:29:14.015600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee718e58c434'
down_revision = 'c327bba3ec85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'citystate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'citystate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
